frontend:
    build: ./agile-frontend
    container_name: nginx_frontend
    volumes:
      - ./nginx.compose.conf:/etc/nginx/nginx.conf:ro 
    ports:
      - "80:80"
    depends_on:
      - backend