#this file will be overwritten by terraform
[master]
master_node ansible_host= # master_public_ip 
[worker]
worker_node ansible_host= # worker_public_ip 
 
[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/my-key.pem
ansible_python_interpreter=/usr/bin/python3